# Generated by Django 3.1.6 on 2021-02-15 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('Player_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('Type', models.CharField(max_length=654)),
                ('Country', models.CharField(max_length=50)),
                ('Debut_year', models.IntegerField()),
                ('ODI_rankings', models.IntegerField()),
                ('T20_rankings', models.IntegerField()),
                ('Test_rankings', models.IntegerField()),
                ('Profile', models.TextField()),
                ('Batting_style', models.CharField(max_length=66)),
                ('BasePrice', models.IntegerField()),
                ('CurrentPrice', models.IntegerField()),
                ('Player_img_1', models.ImageField(upload_to='images/')),
                ('Player_img_2', models.ImageField(upload_to='images_1/')),
            ],
        ),
        migrations.CreateModel(
            name='TEST_STATS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_matches', models.IntegerField()),
                ('test_runs', models.IntegerField()),
                ('test_fours', models.IntegerField()),
                ('test_sixes', models.IntegerField()),
                ('test_ducks', models.IntegerField()),
                ('player_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productdetail.player')),
            ],
        ),
        migrations.CreateModel(
            name='T20I_STATS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t20i_matches', models.IntegerField()),
                ('t20i_runs', models.IntegerField()),
                ('t20i_fours', models.IntegerField()),
                ('t20i_sixes', models.IntegerField()),
                ('t20i_ducks', models.IntegerField()),
                ('player_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productdetail.player')),
            ],
        ),
        migrations.CreateModel(
            name='ODI_STATS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odi_matches', models.IntegerField()),
                ('odi_runs', models.IntegerField()),
                ('odi_fours', models.IntegerField()),
                ('odi_sixes', models.IntegerField()),
                ('odi_ducks', models.IntegerField()),
                ('player_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productdetail.player')),
            ],
        ),
        migrations.CreateModel(
            name='IPL_STATS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipl_matches', models.IntegerField()),
                ('ipl_runs', models.IntegerField()),
                ('ipl_fours', models.IntegerField()),
                ('ipl_sixes', models.IntegerField()),
                ('ipl_ducks', models.IntegerField()),
                ('player_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productdetail.player')),
            ],
        ),
    ]
