# Generated by Django 3.1.6 on 2021-02-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productdetail', '0002_player_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='status',
            new_name='active',
        ),
    ]
