# Generated by Django 3.1.6 on 2021-02-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdetail', '0003_auto_20210218_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='active',
            field=models.BooleanField(default=False, verbose_name=['Active', 'True']),
        ),
    ]
