# Generated by Django 3.1.6 on 2021-02-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdetail', '0004_auto_20210218_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='active',
            field=models.CharField(choices=[('0', 'False'), ('1', 'True')], max_length=2),
        ),
    ]
