# Generated by Django 3.1.6 on 2021-02-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdetail', '0005_auto_20210218_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Player_img_1',
            field=models.ImageField(max_length=500, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='Player_img_2',
            field=models.ImageField(max_length=500, upload_to='images_1/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
